[project]
name = "watchdoguitopy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.11.1",
    "pystray>=0.19.5",
    "watchdog>=6.0.0",
]
